// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpufipopdwvhbevsfoah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwdWZpcG9wZHd2aGJldnNmb2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTcxNzAsImV4cCI6MjA2MDA5MzE3MH0.imA6V8q8VZmbd47UnY_etK1YBYcrUB5ZR4o745lrwfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);